-- 문제 URL = https://school.programmers.co.kr/learn/courses/30/lessons/131533

-- 코드를 입력하세요
SELECT PRODUCT.PRODUCT_CODE, 
PRODUCT.PRICE * SUM(OFFLINE_SALE.SALES_AMOUNT) AS SALES 
FROM PRODUCT 
LEFT JOIN OFFLINE_SALE
ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY OFFLINE_SALE.PRODUCT_ID
HAVING SUM(OFFLINE_SALE.SALES_AMOUNT) >= 1
ORDER BY SALES DESC, PRODUCT_CODE ASC

-- HAVING절이 없어도 정답으로 인식합니다