-- 문제 URL = https://school.programmers.co.kr/learn/courses/30/lessons/59044

-- 코드를 입력하세요
SELECT ANIMAL_INS.NAME, ANIMAL_INS.DATETIME 
FROM ANIMAL_INS 
LEFT JOIN ANIMAL_OUTS 
ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID NOT IN (
    SELECT ANIMAL_OUTS.ANIMAL_ID FROM ANIMAL_OUTS
)
ORDER BY DATETIME ASC
LIMIT 3