-- 문제 URL = https://school.programmers.co.kr/learn/courses/30/lessons/59043

-- 코드를 입력하세요
SELECT answer.ANIMAL_ID,answer.NAME FROM (
    SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.NAME, ANIMAL_INS.DATETIME 
    FROM ANIMAL_INS 
    LEFT JOIN ANIMAL_OUTS 
    ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
    WHERE ANIMAL_INS.DATETIME > ANIMAL_OUTS.DATETIME
    ORDER BY DATETIME ASC
) answer